//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learnApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_lessons
    {
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> order_number { get; set; }
        public int course_id { get; set; }
    
        public virtual course_t course_t { get; set; }
    }
}
