//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learnApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class course_t
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public course_t()
        {
            this.course_lessons = new HashSet<course_lessons>();
            this.trainee_courses = new HashSet<trainee_courses>();
        }
    
        public int id { get; set; }
        public string course_name { get; set; }
        public System.DateTime creation_date { get; set; }
        public int category_id { get; set; }
        public Nullable<int> instructor_id { get; set; }
        public string description { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_lessons> course_lessons { get; set; }
        public virtual instractor instractor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trainee_courses> trainee_courses { get; set; }
    }
}
