//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learnApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class instractor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public instractor()
        {
            this.course_t = new HashSet<course_t>();
        }
    
        public int id { get; set; }
        public string instractor_name { get; set; }
        public string description { get; set; }
        public string email { get; set; }
        public string website { get; set; }
        public System.DateTime creation_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<course_t> course_t { get; set; }
    }
}
