//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace learnApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class enjoy_learn_DBEntities : DbContext
    {
        public enjoy_learn_DBEntities()
            : base("name=enjoy_learn_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<course_lessons> course_lessons { get; set; }
        public virtual DbSet<course_t> course_t { get; set; }
        public virtual DbSet<instractor> instractors { get; set; }
        public virtual DbSet<trainee> trainees { get; set; }
        public virtual DbSet<trainee_courses> trainee_courses { get; set; }
    }
}
